openapi: 3.0.1
info:
  title: Hellodeleg
  version: 1.0.0
servers:
- url: "{server}:{port}/hellodeleg"
  variables:
    server:
      default: http://localhost
    port:
      default: "9236"
paths:
  /sayDelegHello:
    get:
      operationId: operation_get_/sayDelegHello
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
  /sayDelegBye:
    get:
      operationId: operation_get_/sayDelegBye
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
components: {}
